// This file was generated by counterfeiter
package eventfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/receptor/event"
)

type FakeEventSource struct {
	NextStub        func() (event.Event, error)
	nextMutex       sync.RWMutex
	nextArgsForCall []struct{}
	nextReturns struct {
		result1 event.Event
		result2 error
	}
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct{}
}

func (fake *FakeEventSource) Next() (event.Event, error) {
	fake.nextMutex.Lock()
	fake.nextArgsForCall = append(fake.nextArgsForCall, struct{}{})
	fake.nextMutex.Unlock()
	if fake.NextStub != nil {
		return fake.NextStub()
	} else {
		return fake.nextReturns.result1, fake.nextReturns.result2
	}
}

func (fake *FakeEventSource) NextCallCount() int {
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	return len(fake.nextArgsForCall)
}

func (fake *FakeEventSource) NextReturns(result1 event.Event, result2 error) {
	fake.NextStub = nil
	fake.nextReturns = struct {
		result1 event.Event
		result2 error
	}{result1, result2}
}

func (fake *FakeEventSource) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeEventSource) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

var _ event.EventSource = new(FakeEventSource)
