// This file was generated by counterfeiter
package fake_receptor

import (
	"sync"

	"github.com/cloudfoundry-incubator/receptor"
)

type FakeClient struct {
	CreateTaskStub        func(receptor.CreateTaskRequest) error
	createTaskMutex       sync.RWMutex
	createTaskArgsForCall []struct {
		arg1 receptor.CreateTaskRequest
	}
	createTaskReturns struct {
		result1 error
	}
	GetAllTasksStub        func() ([]receptor.TaskResponse, error)
	getAllTasksMutex       sync.RWMutex
	getAllTasksArgsForCall []struct{}
	getAllTasksReturns struct {
		result1 []receptor.TaskResponse
		result2 error
	}
	GetAllTasksByDomainStub        func(domain string) ([]receptor.TaskResponse, error)
	getAllTasksByDomainMutex       sync.RWMutex
	getAllTasksByDomainArgsForCall []struct {
		domain string
	}
	getAllTasksByDomainReturns struct {
		result1 []receptor.TaskResponse
		result2 error
	}
	GetTaskStub        func(taskId string) (receptor.TaskResponse, error)
	getTaskMutex       sync.RWMutex
	getTaskArgsForCall []struct {
		taskId string
	}
	getTaskReturns struct {
		result1 receptor.TaskResponse
		result2 error
	}
	DeleteTaskStub        func(taskId string) error
	deleteTaskMutex       sync.RWMutex
	deleteTaskArgsForCall []struct {
		taskId string
	}
	deleteTaskReturns struct {
		result1 error
	}
}

func (fake *FakeClient) CreateTask(arg1 receptor.CreateTaskRequest) error {
	fake.createTaskMutex.Lock()
	fake.createTaskArgsForCall = append(fake.createTaskArgsForCall, struct {
		arg1 receptor.CreateTaskRequest
	}{arg1})
	fake.createTaskMutex.Unlock()
	if fake.CreateTaskStub != nil {
		return fake.CreateTaskStub(arg1)
	} else {
		return fake.createTaskReturns.result1
	}
}

func (fake *FakeClient) CreateTaskCallCount() int {
	fake.createTaskMutex.RLock()
	defer fake.createTaskMutex.RUnlock()
	return len(fake.createTaskArgsForCall)
}

func (fake *FakeClient) CreateTaskArgsForCall(i int) receptor.CreateTaskRequest {
	fake.createTaskMutex.RLock()
	defer fake.createTaskMutex.RUnlock()
	return fake.createTaskArgsForCall[i].arg1
}

func (fake *FakeClient) CreateTaskReturns(result1 error) {
	fake.CreateTaskStub = nil
	fake.createTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) GetAllTasks() ([]receptor.TaskResponse, error) {
	fake.getAllTasksMutex.Lock()
	fake.getAllTasksArgsForCall = append(fake.getAllTasksArgsForCall, struct{}{})
	fake.getAllTasksMutex.Unlock()
	if fake.GetAllTasksStub != nil {
		return fake.GetAllTasksStub()
	} else {
		return fake.getAllTasksReturns.result1, fake.getAllTasksReturns.result2
	}
}

func (fake *FakeClient) GetAllTasksCallCount() int {
	fake.getAllTasksMutex.RLock()
	defer fake.getAllTasksMutex.RUnlock()
	return len(fake.getAllTasksArgsForCall)
}

func (fake *FakeClient) GetAllTasksReturns(result1 []receptor.TaskResponse, result2 error) {
	fake.GetAllTasksStub = nil
	fake.getAllTasksReturns = struct {
		result1 []receptor.TaskResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetAllTasksByDomain(domain string) ([]receptor.TaskResponse, error) {
	fake.getAllTasksByDomainMutex.Lock()
	fake.getAllTasksByDomainArgsForCall = append(fake.getAllTasksByDomainArgsForCall, struct {
		domain string
	}{domain})
	fake.getAllTasksByDomainMutex.Unlock()
	if fake.GetAllTasksByDomainStub != nil {
		return fake.GetAllTasksByDomainStub(domain)
	} else {
		return fake.getAllTasksByDomainReturns.result1, fake.getAllTasksByDomainReturns.result2
	}
}

func (fake *FakeClient) GetAllTasksByDomainCallCount() int {
	fake.getAllTasksByDomainMutex.RLock()
	defer fake.getAllTasksByDomainMutex.RUnlock()
	return len(fake.getAllTasksByDomainArgsForCall)
}

func (fake *FakeClient) GetAllTasksByDomainArgsForCall(i int) string {
	fake.getAllTasksByDomainMutex.RLock()
	defer fake.getAllTasksByDomainMutex.RUnlock()
	return fake.getAllTasksByDomainArgsForCall[i].domain
}

func (fake *FakeClient) GetAllTasksByDomainReturns(result1 []receptor.TaskResponse, result2 error) {
	fake.GetAllTasksByDomainStub = nil
	fake.getAllTasksByDomainReturns = struct {
		result1 []receptor.TaskResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetTask(taskId string) (receptor.TaskResponse, error) {
	fake.getTaskMutex.Lock()
	fake.getTaskArgsForCall = append(fake.getTaskArgsForCall, struct {
		taskId string
	}{taskId})
	fake.getTaskMutex.Unlock()
	if fake.GetTaskStub != nil {
		return fake.GetTaskStub(taskId)
	} else {
		return fake.getTaskReturns.result1, fake.getTaskReturns.result2
	}
}

func (fake *FakeClient) GetTaskCallCount() int {
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	return len(fake.getTaskArgsForCall)
}

func (fake *FakeClient) GetTaskArgsForCall(i int) string {
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	return fake.getTaskArgsForCall[i].taskId
}

func (fake *FakeClient) GetTaskReturns(result1 receptor.TaskResponse, result2 error) {
	fake.GetTaskStub = nil
	fake.getTaskReturns = struct {
		result1 receptor.TaskResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DeleteTask(taskId string) error {
	fake.deleteTaskMutex.Lock()
	fake.deleteTaskArgsForCall = append(fake.deleteTaskArgsForCall, struct {
		taskId string
	}{taskId})
	fake.deleteTaskMutex.Unlock()
	if fake.DeleteTaskStub != nil {
		return fake.DeleteTaskStub(taskId)
	} else {
		return fake.deleteTaskReturns.result1
	}
}

func (fake *FakeClient) DeleteTaskCallCount() int {
	fake.deleteTaskMutex.RLock()
	defer fake.deleteTaskMutex.RUnlock()
	return len(fake.deleteTaskArgsForCall)
}

func (fake *FakeClient) DeleteTaskArgsForCall(i int) string {
	fake.deleteTaskMutex.RLock()
	defer fake.deleteTaskMutex.RUnlock()
	return fake.deleteTaskArgsForCall[i].taskId
}

func (fake *FakeClient) DeleteTaskReturns(result1 error) {
	fake.DeleteTaskStub = nil
	fake.deleteTaskReturns = struct {
		result1 error
	}{result1}
}

var _ receptor.Client = new(FakeClient)
